# Import

In [1]:
import pandas as pd
import warnings

warnings.simplefilter(action='ignore', category=pd.errors.SettingWithCopyWarning)

# Load

In [2]:
locations = pd.read_csv('../../weather/locations.csv')
measurments = pd.read_csv('../../weather/mesurments.csv')

# Code

In [3]:
mappa_location_codice = {
              0:'S06500_1',
              1:'S06501_1',
              2:'S06400_1',
              3:'S06401_1',
              4:'S06402_1',
              5:'S06404_1',
              6:'S06313_1',
              7:'S06312_1',
              8:'S06310_1',
              9:'S06309_1',
              10:'S06308_1',
              11:'S06306_1',
              12:'S06304_1',
              13:'S06303_1',
              14:'S06302_1',
              15:'S06301_1',
              16:'S06300_1',
              17:'S06322_1',
              18:'S06323_1',
              19:'S06324_1',
              20:'S06325_1',
              21:'S06227_1',
              22:'S06226_1',
              23:'S06225_1',
              24:'S06224_1',
              25:'S06223_1',
              26:'S06222_1',
              27:'S06013_1'}

In [4]:
locations["codice_stazione"] = locations["location_id"].apply(lambda x: mappa_location_codice.get(x))

In [5]:
measurments.head()

,location_id,time,temperature_2m (°C),relative_humidity_2m (%),apparent_temperature (°C),precipitation (mm),rain (mm),snowfall (cm),snow_depth (m),weather_code (wmo code),wind_speed_10m (km/h),wind_speed_100m (km/h),wind_direction_10m (°),wind_direction_100m (°),wind_gusts_10m (km/h),soil_temperature_0_to_7cm (°C)
0,0,2020-01-01T00:00,0.8,97,-2.1,0.0,0.0,0.0,0.0,0,5.6,5.5,75,79,9.7,3.5
1,0,2020-01-01T01:00,-0.3,100,-3.3,0.0,0.0,0.0,0.0,2,6.2,2.4,100,27,11.2,3.8
2,0,2020-01-01T02:00,-0.5,100,-3.4,0.0,0.0,0.0,0.0,2,5.4,2.9,86,360,11.5,3.4
3,0,2020-01-01T03:00,0.2,99,-2.8,0.0,0.0,0.0,0.0,3,5.9,3.9,79,34,11.5,3.2
4,0,2020-01-01T04:00,0.8,99,-2.2,0.0,0.0,0.0,0.0,3,6.6,4.5,81,61,13.0,3.3

### Clean up time in measurment table

In [6]:
measurments = measurments.assign(data_giorno=None)
measurments = measurments.assign(orario=None)

In [7]:
for index, row  in measurments.iterrows():
    if(index % 10000 == 0):
        print("row " + str(index) + "/" +str(measurments.index.max()))
    date,time = measurments.loc[index,"time"].split("T")
    measurments.loc[index,'orario'] = time
    measurments.loc[index,'data_giorno'] = date.replace("-","")

row 0/907847
row 10000/907847
row 20000/907847
row 30000/907847
row 40000/907847
row 50000/907847
row 60000/907847
row 70000/907847
row 80000/907847
row 90000/907847
row 100000/907847
row 110000/907847
row 120000/907847
row 130000/907847
row 140000/907847
row 150000/907847
row 160000/907847
row 170000/907847
row 180000/907847
row 190000/907847
row 200000/907847
row 210000/907847
row 220000/907847
row 230000/907847
row 240000/907847
row 250000/907847
row 260000/907847
row 270000/907847
row 280000/907847
row 290000/907847
row 300000/907847
row 310000/907847
row 320000/907847
row 330000/907847
row 340000/907847
row 350000/907847
row 360000/907847
row 370000/907847
row 380000/907847
row 390000/907847
row 400000/907847
row 410000/907847
row 420000/907847
row 430000/907847
row 440000/907847
row 450000/907847
row 460000/907847
row 470000/907847
row 480000/907847
row 490000/907847
row 500000/907847
row 510000/907847
row 520000/907847
row 530000/907847
row 540000/907847
row 550000/907847
row 560000/907847
row 570000/907847
row 580000/907847
row 590000/907847
row 600000/907847
row 610000/907847
row 620000/907847
row 630000/907847
row 640000/907847
row 650000/907847
row 660000/907847
row 670000/907847
row 680000/907847
row 690000/907847
row 700000/907847
row 710000/907847
row 720000/907847
row 730000/907847
row 740000/907847
row 750000/907847
row 760000/907847
row 770000/907847
row 780000/907847
row 790000/907847
row 800000/907847
row 810000/907847
row 820000/907847
row 830000/907847
row 840000/907847
row 850000/907847
row 860000/907847
row 870000/907847
row 880000/907847
row 890000/907847
row 900000/907847

In [8]:
# Creo una tabella unica
measurments["codice_stazione"] = measurments["location_id"].apply(lambda x: mappa_location_codice.get(x))

In [10]:
measurments = measurments.rename(columns={'temperature_2m (°C)': 'temperature',
                                          'apparent_temperature (°C)' : 'app_temp',
                                          'relative_humidity_2m (%)' : 'humidity',
                                          'precipitation (mm)' : 'precipitation',
                                          'rain (mm)' : 'rain', 
                                          'snowfall (cm)':'snow_fall',
                                          'snow_depth (m)':'snow_depth',
                                          'weather_code (wmo code)' : 'wmo_code',
                                          'wind_speed_10m (km/h)':'wind_speed_10m',
                                          'wind_speed_100m (km/h)':'wind_speed_100m',
                                          'wind_direction_10m (°)':'wind_dir_10m',
                                          'wind_direction_100m (°)':'wind_dir_100m',
                                          'wind_gusts_10m (km/h)' : 'wind_gusts',
                                          'soil_temperature_0_to_7cm (°C)':'soil_temperature'
                                         })

measurments['data_giorno'] = measurments['data_giorno'].astype(str)

In [11]:
measurments.to_csv('../processed_files/measurments_preprocessing.csv')

In [12]:
measurments

,location_id,time,temperature,humidity,app_temp,precipitation,rain,snow_fall,snow_depth,wmo_code,wind_speed_10m,wind_speed_100m,wind_dir_10m,wind_dir_100m,wind_gusts,soil_temperature,data_giorno,orario,codice_stazione
0,0,2020-01-01T00:00,0.8,97,-2.1,0.0,0.0,0.0,0.0,0,5.6,5.5,75,79,9.7,3.5,20200101,00:00,S06500_1
1,0,2020-01-01T01:00,-0.3,100,-3.3,0.0,0.0,0.0,0.0,2,6.2,2.4,100,27,11.2,3.8,20200101,01:00,S06500_1
2,0,2020-01-01T02:00,-0.5,100,-3.4,0.0,0.0,0.0,0.0,2,5.4,2.9,86,360,11.5,3.4,20200101,02:00,S06500_1
3,0,2020-01-01T03:00,0.2,99,-2.8,0.0,0.0,0.0,0.0,3,5.9,3.9,79,34,11.5,3.2,20200101,03:00,S06500_1
4,0,2020-01-01T04:00,0.8,99,-2.2,0.0,0.0,0.0,0.0,3,6.6,4.5,81,61,13.0,3.3,20200101,04:00,S06500_1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
907843,26,2023-11-01T19:00,13.3,98,14.1,0.3,0.3,0.0,0.0,51,1.1,6.8,342,183,13.0,14.6,20231101,19:00,S06222_1
907844,26,2023-11-01T20:00,13.2,99,13.3,0.9,0.9,0.0,0.0,53,6.0,12.0,163,173,24.1,14.5,20231101,20:00,S06222_1
907845,26,2023-11-01T21:00,13.4,99,13.9,0.8,0.8,0.0,0.0,53,3.4,9.1,108,162,21.2,14.5,20231101,21:00,S06222_1
907846,26,2023-11-01T22:00,13.5,99,13.7,1.2,1.2,0.0,0.0,55,5.7,12.1,125,157,18.4,14.5,20231101,22:00,S06222_1
907847,26,2023-11-01T23:00,13.3,99,13.9,1.3,1.3,0.0,0.0,61,2.9,6.4,83,153,19.1,14.5,20231101,23:00,S06222_1